version: '3'
services:

    db:
        container_name: netapi_db
        image: mysql:8.0.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - netapi_db_vol:/var/lib/mysql
        networks:
            - netapi_net

    queue:
        container_name: netapi_queue
        image: rabbitmq:3.6.9
        ports:
            - "5672:5672"
            - "15672:15672"
        command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
        volumes:
            - ./scripts/docker/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
            - ./scripts/docker/definitions.json:/etc/rabbitmq/definitions.json:ro
        networks:
            - netapi_net

    cache:
        container_name: netapi_cache
        image: memcached:1.4.33
        command:
            - "-I 5m"
        ports:
            - "11211"
        networks:
            - netapi_net

    celery:
        container_name: netapi_celery
        image: globocom/networkapi:latest
        command: sh scripts/docker/docker-start-celery.sh
        env_file:
            - scripts/docker/netapi.env
        volumes:
          - .:/netapi
        networks:
            - netapi_net
        links:
            - db:netapi_db
            - queue:netapi_queue
            - cache:netapi_cache
        depends_on:
          - queue

    netapi:
        container_name: netapi_app
        image: networkapi:latest
        restart: always
        ports:
            - "127.0.0.1:8000:8000"
            - "127.0.0.1:8001:8001"
        env_file:
            - scripts/docker/netapi.env
        volumes:
            - .:/netapi
        networks:
            - netapi_net
        depends_on:
            - db
            - queue
            - cache
        links:
            - db:netapi_db
        external_links:
            - netapi_graylog2
            - cache:netapi_cache
            - odl:netapi_odl
            - queue:netapi_queue

volumes:
    netapi_db_vol:

networks:
    netapi_net:
